import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import {
  // downloadFromBlobPartFile,
  // downloadFromUint8Array,
  getAsByteArray,
  readFileAsText,
  zip,
  isZipFileUsingPassword,
} from '@/utils';

const inter = Inter({ subsets: ['latin'] });

const env = process.env.NEXT_PUBLIC_ENV;
if (env) console.log('🚀 ~ env', env);

const handleFolderSelected = async (event: {
  target: { files: FileList | null };
}): Promise<void> => {
  const files = event.target.files;
  if (!files) throw new Error('Files are not found!');

  console.log('🚀 ~ event.target', event.target);
  console.log('🚀 ~ files', files);

  const firstFile = files[0];
  if (!files) throw new Error('First file is not found!');

  readFileAsText(firstFile);

  const byteFile = await getAsByteArray(firstFile);
  console.log('🚀 ~ byteFile', byteFile);
  const zippedFile = zip(byteFile);
  console.log('🚀 ~ test', zippedFile);
  const isUsingPass = await isZipFileUsingPassword(firstFile);
  console.log('🚀 ~ isUsingPass', isUsingPass);

  // downloadFromUint8Array(zippedFile);
  // downloadFromBlobPartFile(zippedFile);
};

const handleFileSelected = async (event: {
  target: { files: FileList | null };
}): Promise<void> => {
  const files = event.target.files;
  if (!files) throw new Error('Files are not found!');

  console.log('🚀 ~ event.target', event.target);
  console.log('🚀 ~ files', files);

  const firstFile = files[0];
  if (!firstFile) throw new Error('First file is not found!');

  const byteFile = await getAsByteArray(firstFile);
  console.log('🚀 ~ byteFile', byteFile);

  const zippedFile = zip(byteFile);
  console.log('🚀 ~ test', zippedFile);

  const isUsingPass = await isZipFileUsingPassword(firstFile);
  console.log('🚀 ~ isUsingPass', isUsingPass);

  // unzip
  // console.log('start to unzip');

  // const unzippedFile = unzip(byteFile);
  // console.log('🚀 ~ unzippedFile', unzippedFile);

  // console.log('end to unzip');

  // downloadFromUint8Array(zippedFile);
  // downloadFromBlobPartFile(zippedFile);
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <input
            type="file"
            directory="directory"
            multiple
            webkitdirectory="webkitdirectory"
            onChange={handleFolderSelected}
          />
          <input type="file" multiple onChange={handleFileSelected} />
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
